name: Integration Tests

on:
  push:

jobs:
  build:
    if: "!startsWith(github.ref, 'refs/tags/')"

    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r api/requirements.txt

    - name: Make script executable
      run: chmod +x ./integration_tests.sh
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: ./integration_tests.sh
      env:
        MAINTAINABILITY_API_KEY: ${{ secrets.MAINTAINABILITY_API_KEY }}
