name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Publish Package
      id: publish_step
      continue-on-error: true
      uses: celsiusnarhwal/poetry-publish@v2
      with:
        python-version: '3.10'
        poetry-version: 1.3.1
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        build: true

    - name: Check Publish Outcome
      run: echo "Publish step completed with ${{ steps.publish_step.outcome }} status."
