name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Get Current Version
      id: get_version
      run: echo "CURRENT_VERSION=$(poetry version -s)" >> $GITHUB_ENV

    - name: Get Latest Tag
      id: get_tag
      run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Check and Publish
      run: |
        if [[ "$CURRENT_VERSION" != "$LATEST_TAG" ]]; then
          git config --global user.email "voynow99@gmail.com"
          git config --global user.name "voynow"
          git tag $CURRENT_VERSION
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/voynow/maintainability.git
          git push origin $CURRENT_VERSION
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
